name: Polaris Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    # 修改這裡使用你的 self-hosted runner
    runs-on: self-hosted  
    
    # 可以添加 runner 的標籤
    # 根據你的設置,runner 有: 'self-hosted', 'Linux', 'X64' 這些標籤
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Polaris Scan
      uses: synopsys-sig/polaris-action@v1
      with:
        polaris_server_url: 'https://polaris.synopsys.com'
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_application_name: 'myWebgoat'
        polaris_project_name: 'myWebgoat'
        polaris_branch_name: ${{ github.ref_name }}
