name: Polaris Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Polaris Scan
      uses: synopsys-sig/polaris-action@v1
      with:
        polaris_server_url: 'https://polaris.synopsys.com'
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_application_name: 'my-app'
        polaris_project_name: 'my-project'
        polaris_branch_name: ${{ github.ref_name }}
