name: Polaris Scan

on:
  push:
    branches: [ main, master ]  # 增加 master 分支
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 添加手動觸發選項
  
jobs:
  security:
    runs-on: self-hosted
    
    steps:
    - name: Echo Test  # 增加測試步驟
      run: |
        echo "Starting workflow..."
        echo "Current branch is ${{ github.ref }}"
    
    - uses: actions/checkout@v2
    
    - name: Polaris Scan
      uses: synopsys-sig/polaris-action@v1
      with:
        polaris_server_url: 'https://poc.polaris.blackduck.com'
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_application_name: 'myWebgoat'
        polaris_project_name: 'myWebgoat'
        polaris_branch_name: ${{ github.ref_name }}
