name: Polaris Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security:
    runs-on: self-hosted
    environment: polaris 
    steps:
    - uses: actions/checkout@v2
    
    # 添加 Java 設置
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'microsoft'
        cache: maven
        
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2.0.0
      with:
        polaris_server_url: 'https://poc.polaris.blackduck.com'
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_application_name: 'myWebgoat'
        polaris_project_name: 'myWebgoat'
        polaris_branch_name: ${{ github.ref_name }}
        polaris_assessment_types: 'SAST,SCA'
