name: Polaris Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security:
    runs-on: self-hosted  # 確保 self-hosted runner 已安裝 Java 23
    environment: polaris 
    steps:
    - uses: actions/checkout@v4
    
    # 檢查 Java 版本
    - name: Check Java version
      run: java -version
        
    - name: Polaris Scan
      uses: synopsys-sig/synopsys-action@v1.13.0
      with:
        polaris_server_url: 'https://poc.polaris.blackduck.com'
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_application_name: 'myWebgoat'
        polaris_project_name: 'myWebgoat'
        polaris_branch_name: ${{ github.ref_name }}
        polaris_assessment_types: 'SAST,SCA'
